image: docker:20.10
variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
services:
  - docker:20.10-dind

build-master:
  tags: 
    - docker
  stage: build
  script:
  - docker build -t myimage .
  only:
  - master
