services:
  db: 
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  app: 
    build: .
    command: node server.js
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: todos
      DB_USER: todos
      DB_PASSWORD: password
volumes:
  postgres: